/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_yadaw_audio_Asio */

#ifndef _Included_dk_yadaw_audio_Asio
#define _Included_dk_yadaw_audio_Asio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioLibInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioLibInit
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetFirstDriver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_yadaw_audio_Asio_asioGetFirstDriver
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetNextDriver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_yadaw_audio_Asio_asioGetNextDriver
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioLoadDriver
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dk_yadaw_audio_Asio_asioLoadDriver
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dk_yadaw_audio_Asio_asioInit
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetSamplerate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_dk_yadaw_audio_Asio_asioGetSamplerate
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetSamplePos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dk_yadaw_audio_Asio_asioGetSamplePos
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioGetBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetOutputLatency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioGetOutputLatency
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetInputLatency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioGetInputLatency
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetAvailableInputs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioGetAvailableInputs
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetAvailableOutputs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioGetAvailableOutputs
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioClearArmedChannels
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioClearArmedChannels
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioArmInput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioArmInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioArmOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioArmOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioPrepBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioPrepBuffers
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioSetOutputSamples
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioSetOutputSamples
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioGetInputSamples
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_dk_yadaw_audio_Asio_asioGetInputSamples
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_yadaw_audio_Asio_asioStart
  (JNIEnv *, jobject);

/*
 * Class:     dk_yadaw_audio_Asio
 * Method:    asioStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_yadaw_audio_Asio_asioStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
